### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by nicolast0604** [shicai/MobileNet-Caffe#89]
python3 eval_image.py --proto mobilenet_deploy.prototxt --model mobilenet.caffemodel --image ./cat.jpg

Traceback (most recent call last):
  File "eval_image.py", line 64, in <module>
    eval()
  File "eval_image.py", line 36, in eval
    im = im[:, off:off + h]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by lcj820** [comment]
我已收到你的邮件，谢谢

**Comment by changan1tao** [comment]
您好，您的邮件我已收到

**Comment by changan1tao** [comment]
您好，您的邮件我已收到

**Comment by lcj820** [comment]
我已收到你的邮件，谢谢
